import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers"
import { SidebarProvider} from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  return (
    <html lang="en">
        <body>
          <SidebarProvider defaultOpen={defaultOpen} > {/* provides the sidebar context. app
          should always be wrapped in a SidebarProvider*/}
             <AppSidebar/> {/* the actual sidebar component */}
              {children}
          </SidebarProvider>
        </body>
    </html>
  );
}
